FarmersMarketTeam/FarmersMarket

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/main/java/com/theironyard/entities/User.java
- src/main/java/com/theironyard/services/UserRepository.java
- src/main/java/com/theironyard/utilities/PasswordStorage.java
second import from backend.
1. added create account routes (add, put, delete)
2. hardcoded admin
3. made route for admin to accept or deny new users
4. route to render all users to admin and buyers, but not farmers
> Second import from Backend. 

- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
third import. 
main application is broken/not running. rebuilt the Jar…
… but its still not running. but its still not running.
> third import from backend.

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/main/java/com/theironyard/services/UserRepository.java
fixed issue launching and updated jar
> fixed the error

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/main/java/com/theironyard/entities/User.java
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
fifth import from backend.
1. jar rebuilt and works when running
2. createUser route was edited
3. test for createUser is working.
4. hardcoded Admin is appearing in H2 Database and  JSON /users route
> fifth import from backend

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
fixed login route
fixed test for login route
> 7th import from backend

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
added a route to find one user. /users/{id}
> 8th import from backend

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/main/java/com/theironyard/entities/Inventory.java
- src/main/java/com/theironyard/entities/User.java
- src/main/java/com/theironyard/services/InventoryRepository.java
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
9th import from backend.
1. added class of Inventory
2. added CRUD routes for inventory
3. added tests for inventory routes
> 9th import from backend

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
11th import from backend. changed the login route back to previous ve…
…rsion. its working with backend without the changes
> 11th import from backend

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/main/java/com/theironyard/entities/Purchase.java
- src/main/java/com/theironyard/services/PurchaseRepository.java
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
12th import. added Purchase class/table. rebuilt jar.
> 12th import from backend

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
13th import from backend. changed the createUser route from void to return a User object.
> 13th import from backend

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/main/java/com/theironyard/entities/Inventory.java
- src/main/java/com/theironyard/services/InventoryRepository.java
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
also removed some unneeded code from the inventory class parameters and adjusted some of the tests to compensate for the changes
> adjusted routes for inventory

- src/main/java/com/theironyard/entities/User.java
moved "passwordValidate" to the order in constructor that frontend wanted, right after passwordHash
> 15th import from backend.

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/main/java/com/theironyard/entities/Inventory.java
19th import from backend.
added a new constructor in inventory which doesnt include the "user".
rebuilt jar file
> 19th import from backend

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/main/java/com/theironyard/services/PurchaseRepository.java
got this running with an admin specific get route for purchases and made a delete route for purchases as well, though this only works on purchases awaiting validation as written
> added new routes for admin view of purchases and for deleting purchases

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/main/java/com/theironyard/services/InventoryRepository.java
added a route to get inventory by username
> 23rd import from backend.

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
updated validation and working on new tests
> fixed merge conflicts in pull with new route available

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
rebuilt jar file and hardcoded an inventory item to HankFarmer
> 28th import from backend.

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/main/java/com/theironyard/entities/User.java
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
29th import from backend.
rebuilt jar file and wrote a test and also typed in all the tests we will need.
> 29th import from backend

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/main/java/com/theironyard/entities/Order.java
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
also added an admin specific version "/orders/admin/{buyerId}" which posts an order request in much the same way but allows an admin to do it using the path variable buyerId to get the buyer for the object. Also removed dateDesiredByBuyer for simplicity for the time being.
> updated orders post route

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
now takes a path variable to set the inventory
> changed orders post routes again

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
32nd import from backend.
rebuilt jar file and changed a get orders route name
> 32nd import from backend

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
fixed a bug in validation in the authorize orders route.
> 33nd import from backend.

- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/main/resources/application.properties
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
finished writing tests for all routes, and updated the jar
> 36th import from the backend

- .gitignore
- public/bundle.js
- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
38th commit from backend.
rebuilt jar. cleaned up slashed // out comments that werent needed
> 38th commit from backend

- RequirementsDocument
- src/main/java/com/theironyard/controllers/FarmersMarketController.java
- src/test/java/com/theironyard/FarmersMarketApplicationTests.java
39th commit from backend.
rebuilt jar. cleaned up more of the controller AND EDITED THE REQUIREMENTS DOCUMENT
> 39th commit from backend
